### ISSUE TITLE
Database structure concept

### ISSUE THREAD

**Issue by Jmion** [basbeu/theSofties#74]

**Comment by alexander-san** [comment]
reference #13

**Comment by alexander-san** [comment]
[Database - 05.10.2018.pdf](https://github.com/basbeu/theSofties/files/2450142/Database.-.05.10.2018.pdf)

**Comment by alexander-san** [comment]
For the relevant implementation #76 & #80 please refer to the PDF I added above.

With this I close the issue

**Comment by nicolasp9-dev** [comment]
Hey, do you think it would be possible to have a more clear document, like some excels sheets with tables, with contents examples and links between data ? It would make the implementation more easier. Thanks
